#!/bin/sh
set -e

if [ -z "${1}" ]; then
	echo "usage: $0 package.tbz2 <SYSROOT>"
        echo example: $0 ssh-mtconfig-4.0.4.tbz2
        exit
fi

function banner {
echo "================================================================"
echo "$1"
echo "================================================================"
}

if [ -z "${2}" ]; then
  export SYSROOT="/"
else
  export SYSROOT="${2}"
  export CBUILD=$(portageq envvar CHOST) 
  export PORTAGE_CONFIGROOT=${SYSROOT} 
  export ROOT=${SYSROOT}
  export PORTAGE_BINHOST=""
  export FEATURES="-getbinpkg"
fi

banner "Create the workdir, tbz2file"
TBZ2FILE="$1"
WORKDIR="${SYSROOT}/tmp/`date +%Y%m%d_%H%M%S`"
TBZ2FILE_XPAK=$(echo "${WORKDIR}/`basename ${1}`" | sed -e 's/\.tbz2/\.xpak/g')
echo "TBZ2FILE="$TBZ2FILE
echo "WORKDIR="$WORKDIR
echo "TBZ2FILE_XPAK="$TBZ2FILE_XPAK
mkdir -pv ${WORKDIR}

banner "Copying the file to the workdir"
cp -v ${TBZ2FILE} ${WORKDIR}

banner "Uncompressing the tbz2file"
cd ${WORKDIR}
qtbz2 -v -x ${TBZ2FILE}
PF="`qxpak -O -x ${TBZ2FILE_XPAK} PF`"
CATEGORY="`qxpak -O -x ${TBZ2FILE_XPAK} CATEGORY`"
echo "PF="$PF
echo "CATEGORY="$CATEGORY
echo "TBZ2FILE_XPAK="$TBZ2FILE_XPAK

banner "Emerging $TBZ2FILE"
MYPKGDIR="${WORKDIR}/All"
mkdir -pv "${MYPKGDIR}"
cp -v "${TBZ2FILE}" "${MYPKGDIR}"
PKGDIR=${WORKDIR} emerge -K "=${CATEGORY}/${PF}"
